### PR TITLE
Create Sum of series(School)

### PR DESCRIPTION
**Pull request by R-s-rawat**
upcoming Daily quiz and ques

### CODE REVIEW

**Comment by R-s-rawat** [comment]
I uploaded my most basic started ques for anyone help and motivation

**Comment by NaimulHasanEmon** [comment]
I am not getting. what i have to do?

**Comment by R-s-rawat** [comment]
I will just upload my daily ques here with my ans approach
as i do development daily from all day

**Comment by R-s-rawat** [comment]
As i code daily so i want accountability to do dsa daily

**Comment by NaimulHasanEmon** [comment]
i am learning dsa. i've started recently

**Comment by R-s-rawat** [comment]
Yes I have js background so oops target

**Comment by R-s-rawat** [comment]
I will learn from your solutions while uploading mine so i can review or you can say you are the admin with responsibility

**Comment by NaimulHasanEmon** [comment]
I understand. I hope my code will be helpful to you and I can also learn from yours.

**Pull request closed without merging**
